sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8
services:
  - memcached
  - redis
script:
  # disable scoverage until it's published for 2.13.0-M4
  #- sbt +coverage +test +doc/tut
  #- sbt +coverageReport
  - sbt +test doc/tut
  - sbt ++2.13.0-M4 {coreJVM,guava,memcached,ehcache,redis,cache2k,caffeine,ohc,scalaz72}/test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
